site_name: Cooked!
site_url: https://bedrockcommands.github.io/Cooked/
repo_url: "https://github.com/BedrockCommands/Cooked"
repo_name: "Cooked"

copyright: Copyright &copy; 2025 Bedrock Commands Community (BCC)
extra:
  generator: false
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.com/servers/bedrock-commands-community-924894457894174740
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/@bccommunuty

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
  palette:
    - scheme: default
      primary: burgundy
      accent: gold
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: burgundy
      accent: gold
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
