site_name: 🍳 Cooked!
site_url: https://bedrockcommands.github.io/Cooked/
repo_url: "https://github.com/BedrockCommands/Cooked"
repo_name: "Cooked"

copyright: |
  Copyright &copy; 2025 Bedrock Commands Community (BCC) <br>
  Website Template by <a href="https://squidfunk.github.io/mkdocs-material/">MkDocs</a> – Licensed under the <a href="https://opensource.org/licenses/BSD-2-Clause">BSD-2-Clause License</a>
extra:
  generator: false
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.com/servers/bedrock-commands-community-924894457894174740
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/@bccommunuty

theme:
  name: material
  favicon: "assets/logo.png"
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
  palette:
    - scheme: default
      primary: brown
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: brown
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  logo: "assets/logo.png"
  icon:
    repo: fontawesome/brands/github

extra_css:
  - stylesheets/extra.css
